# -*- coding: utf-8 -*-
"""CLASS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNCr_FQ-40JY8OX9GU_P_fYGhWgUSdpj

object oriented programming
"""

class Student:
    print("Hello")
a = Student()
print(type(a))

class Student:
    @staticmethod
    def func():
      print("Hi")
Student.func()

class Student:
  def func(self):
    print("Hi")
a = Student()
a.func()

"""Class Object Atrribute"""

class Student:
  year = '2026'
  def func():
    print("Hi")
x = Student()
x.year

class Student:
  year = '2026'
  def func(self):
    print("Hi",self.year)
x = Student()
x.func()

"""Attribute of an object"""

class Student:
  def __init__(self,name):
    self.name = name
ak = Student(name = 'Ak !')
print(ak.name)

from os import name
class Student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
ak = Student(name = 'Ak !', age = 20)
champ = Student(name = 'champ', age = 21)
print(ak.name)
print(champ.name)

class Student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
ak = Student(name = 'Ak !', age = 20)
champ = Student(name = 'champ', age = 21)
print(ak.name,ak.age)
print(champ.name,champ.age)

class Student:
  Total = 500
  def __init__(self,marks):
    self.marks=marks
    print("Initialized..")
  def findloss(self):
    return self.Total-self.marks
  def findPercentage(self):
    return self.marks/self.Total*100
a = Student(marks=450)
print('Total marks: ',a.Total)
print('lossed Marks',a.findloss())
print('percentage is',a.findPercentage)

"""Special Methods"""

class Student:
  def __init__(self,name,marks,gender):
    self.name=name
    self.marks=marks
    self.gender=gender
    print("Initialized..")
  def __len__(self):
    return self.marks
  def __str__(self):
    return "Name: %s | Marks: %s | Gender: %s" %(self.name,self.marks,self.gender)
  def __del__(self):
    print("Student datbase is deleted")
a = Student('champ',450,'male')
print(a)
print('Marks: ',len(a))
del a

"""Inheritence"""

class Elon:
  def __init__(self):
    print("Profile created")
  def name(self):
    print("Elon")
  def age(self):
    print("40")
class SpaceX(Elon):
  def __init__(self):
    Elon.__init__(self)
    print("Company Profile created")
  def name(self):
    print("SpaceX")
  def type(self):
    print("Private Space travel")
a = SpaceX()

a.name()
a.age()

"""Polymorphism"""

class Elon:
  def __init__(self,name):
    self.name = name
  def type(self):
    return "Artist"
class Sundar:
  def __init__(self,name):
    self.name = name
  def type(self):
    return "CEO"
person1 = Elon("Elon")
person2 = Sundar("Sundar")
print(person1.type())
print(person2.type())
for i in[person1,person2]:
  print(i.name)
  print(i.type())
  print("************")